"""
Django settings for VRWare project.
Generated by 'django-admin startproject' using Django 2.2.4.
For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from configparser import RawConfigParser
import logging

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) # /home/logan/FCRWebApp/Backend


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q*c06+=)tz%pcs=a5#*mcx&@zg$pmle-cdy*lxjgxq9ydgd=vi'

# SECURITY WARNING: don't run with debug turned on in production!
# NOTE: 'False' removes styles from django-admin
DEBUG = True # True by default. Needed to change it to False so that we can see what a live site would show 

# was [] by default. Needed to change to 127.0.0.1 when we changed Debug to False
ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'profile', 
    'audioanalysis',
    'users',
    'corsheaders', 
]

# Removed     'django.middleware.csrf.CsrfViewMiddleware', (https://stackoverflow.com/a/22812799/9599554)
MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

# docs.djangoproject.com/en/3.0/ref/settings/#std:setting-CSRF_USE_SESSIONS
CSRF_USE_SESSIONS = False

# docs.djangoproject.com/en/3.0/ref/settings/#std:setting-CSRF_COOKIE_HTTPONLY
CSRF_COOKIE_HTTPONLY = False

SESSION_COOKIE_AGE = 1209600

# SESSION_COOKIE_HTTPONLY = False

# Leaving this setting off isn't a good idea because an attacker could capture an unencrypted session cookie with a packet sniffer and user the cookie to hijack the user's session
SESSION_COOKIE_SECURE = False

SESSION_EXPIRE_AT_BROWSER_CLOSE = False

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_REGEX_WHITELIST = [
    'http://localhost:3000',
]

ROOT_URLCONF = 'VRWare.urls'
# needed to add 'templates' so that Django will know to look for the new templates folder
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'profile/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'VRWare.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

config = RawConfigParser()
config.read('/home/logan/settings.ini')

DJANGO_ENGINE = config.get('database', 'database_engine')
DJANGO_NAME = config.get('database', 'database_name')
DJANGO_USER = config.get('database', 'database_user')
DJANGO_PASSWORD = config.get('database', 'database_password')
DJANGO_HOST = config.get('database', 'database_host')
DJANGO_PORT = config.get('database', 'database_port')

DATABASES = {
    'default': {
        'ENGINE': DJANGO_ENGINE, 
        'NAME': DJANGO_NAME, 
        'USER': DJANGO_USER, 
        'PASSWORD': DJANGO_PASSWORD, 
        'HOST': DJANGO_HOST, 
        'PORT': DJANGO_PORT
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE':10, 
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'VRWare.authentication.TokenAuthentication.TokenAuthentication'
        'rest_framework.authentication.SessionAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': []
}

AUTH_USER_MODEL = 'users.CustomUser'

# For file uploads
# The location of the iploaded file will be in MEDIA_ROOT/images
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# I don't think this is neeeed
#MEDIA_URL = '/media/'

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

# https://stackoverflow.com/questions/35032159/how-to-set-simple-password-in-django-1-9/35032185
"""
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
"""


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False, 
    'handlers': {
        'file': {
            'level': 'DEBUG', 
            'class': 'logging.FileHandler',
            'filename': '/home/logan/FCRWebApp/Backend/logs/debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level':os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },
    },
}

# set S3 as the place to store your files.

"""
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_ACCESS_KEY_ID = 'AKIA3TP3EASLVVHRHEZ7'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME  = 'vrwarebucket'
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-agent=86400'
}
AWS_LOCATION = 'static'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'mysite/static'),
]
STATIC_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
AWS_DEFAULT_ACL = None
"""
