# Generated by Django 3.0.5 on 2020-05-03 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('s3_url', models.URLField(default='RANDOM TEXT', max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audio_files_table',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pronunciation_posteriori_probability_score_percentage', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('syllables_count', models.IntegerField(null=True)),
                ('pauses_count', models.IntegerField(null=True)),
                ('rate_of_speech', models.IntegerField(null=True)),
                ('articulation_rate', models.IntegerField(null=True)),
                ('speaking_duration', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('original_duration', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('audio_file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='audioanalysis.Audio')),
            ],
            options={
                'db_table': 'metrics_table',
            },
        ),
    ]
