# Generated by Django 3.0.5 on 2020-04-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioanalysis', '0002_audio_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=128),
            preserve_default=False,
        ),
    ]
