# Generated by Django 3.0.5 on 2020-05-03 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audioanalysis', '0003_audio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronunciation_posteriori_probability_score_percentage', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('syllables_count', models.IntegerField(null=True)),
                ('pauses_count', models.IntegerField(null=True)),
                ('rate_of_speech', models.IntegerField(null=True)),
                ('articulation_rate', models.IntegerField(null=True)),
                ('speaking_duration', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('original_duration', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('audio_file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='audioanalysis.Audio')),
            ],
            options={
                'db_table': 'metrics_table',
            },
        ),
    ]
