# Generated by Django 3.0.5 on 2020-05-03 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioanalysis', '0005_remove_audio_audio_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='audio',
            table='audio_files_table',
        ),
    ]
