# Generated by Django 3.0.5 on 2020-04-11 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audioanalysis', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='audio_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audioanalysis.Audio'),
        ),
    ]
