# Generated by Django 3.0.5 on 2020-05-03 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='audio_file',
        ),
    ]
